reset of 001,002, successful. added regional configurations. starting to work on ci jobs

diff --git a/.github/workflows/003-001-deploy-vpc.yml b/.github/workflows/003-001-deploy-vpc.yml
--- a/.github/workflows/003-001-deploy-vpc.yml
+++ b/.github/workflows/003-001-deploy-vpc.yml
@@ -1,12 +1,259 @@
 name: 003-001 Deploy VPC
 on:
+  #  push:
   workflow_dispatch:
+    inputs:
+      project-name:
+        description: "Custom Name"
+        required: false
+        default: "ci_vpc"
+      project-id:
+        description: "Custom Id"
+        required: false
+        default: "001"
+      project-postfix:
+        description: "Random string applied to the end of resource names for uniqueness - should match S3 bucket"
+        required: true
+        default: "xi7egjwf"
+      aws-region:
+        description: "Which region is being deployed to"
+        required: false
+        type: choice
+        options:
+          - us-east-2
+          - us-west-2
+        default: us-east-2
+      environment:
+        description: "Target Environment"
+        required: false
+        type: choice
+        options:
+          - dev
+          - test
+          - staging
+          - prod
+      environment-prefix:
+        description: "Should resources be prefixed with environment?"
+        required: true
+        type: boolean
+        default: false
+      vpc-cidr-block:
+        description: "VPC Cidr block"
+        required: false
+        default: "10.0.0.0/16"
+      vpc-public-subnet-01:
+        description: "Public subnet"
+        required: false
+        default: "10.0.1.0/24"
+      vpc-public-subnet-02:
+        description: "Public subnet"
+        required: false
+        default: "10.0.2.0/24"
+      vpc-private-subnet-01:
+        description: "Private subnet"
+        required: false
+        default: "10.0.3.0/24"
+      vpc-private-subnet-02:
+        description: "Private subnet"
+        required: false
+        default: "10.0.4.0/24"
+      vpc-public-route-table:
+        description: "Public route table cidr block"
+        required: false
+        default: "0.0.0.0/0"
+      vpc-private-route-table:
+        description: "Private route table cidr block"
+        required: false
+        default: "0.0.0.0/0"
+
+permissions:
+  actions: write
+  id-token: write
 
 jobs:
-  tflint-account-resources:
-    name: Run TFLint - (Project Account Resources)
+
+  verify:
     runs-on: ubuntu-latest
+    outputs:
+      checkov_vpc_status: ${{ steps.checkov-result.outputs.status }}
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v6
+      # Step 1: Find latest workflow run and the artifact
+      - name: Resolve checkov-ci-vpc artifact
+        id: artifact
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          script: |
+            const workflowFile = "tf-static-analysis.yml";
+            const { owner, repo } = context.repo;
+
+            // get the latest completed run
+            const runs = await github.rest.actions.listWorkflowRuns({
+              owner,
+              repo,
+              workflow_id: workflowFile,
+              status: "completed",
+              per_page: 1,
+            });
+
+            if (!runs.data.workflow_runs.length) {
+              core.setFailed("No completed workflow runs found");
+              return;
+            }
+
+            const runId = runs.data.workflow_runs[0].id;
+            core.info(`Using workflow run ID: ${runId}`);
+
+            // list artifacts
+            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
+              owner,
+              repo,
+              run_id: runId,
+            });
+
+            const checkovArtifact = artifacts.data.artifacts.find(a => a.name === "checkov-ci-vpc");
+
+            if (!checkovArtifact) {
+              core.setFailed("Artifact checkov-ci-vpc not found");
+              return;
+            }
+
+            core.setOutput("artifact_url", checkovArtifact.archive_download_url)
+
+      # Step 2: Download artifact, print result.txt, and set output
+      - name: Download and verify checkov-ci-vpc
+        id: checkov-result
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -euo pipefail
+
+          ARTIFACT_URL="${{ steps.artifact.outputs.artifact_url }}"
+          ARTIFACT_NAME="checkov-ci-vpc"
+
+          echo "🔍 Downloading $ARTIFACT_NAME"
+          curl -sSL \
+            -H "Authorization: Bearer $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github+json" \
+            "$ARTIFACT_URL" \
+            -o "$ARTIFACT_NAME.zip"
+
+          unzip -o "$ARTIFACT_NAME.zip" -d "$ARTIFACT_NAME"
+
+          RESULT_FILE="$ARTIFACT_NAME/result.txt"
+
+          if [[ ! -f "$RESULT_FILE" ]]; then
+            echo "❌ result.txt missing!"
+            echo "status=failure" >> $GITHUB_OUTPUT
+            exit 1
+          fi
+
+          echo "📄 Contents of $RESULT_FILE:"
+          cat "$RESULT_FILE"
+          echo "-------------------------"
+
+          # Read status
+          STATUS=$(grep -Eo "status=.+$" "$RESULT_FILE" | cut -d= -f2)
+
+          echo "status=$STATUS" >> $GITHUB_OUTPUT
+
+          if [[ "$STATUS" != "success" ]]; then
+            echo "❌ Checkov CI VPC job failed!"
+            exit 1
+          else
+            echo "✅ Checkov CI VPC job succeeded!"
+          fi
+
+  terraform-deploy-us-east-2:
+    if: ${{ needs.verify.outputs.checkov_vpc_status == 'success' && inputs.aws-region == 'us-east-2' }}
+    needs: verify
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: aws/tools/003-once-to-many-per-region/001-setup-vpc/us-east-2
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v5.0.0
+        with:
+          aws-region: ${{ secrets.DEV_AWS_REGION }}               # REQUIRED
+          role-to-assume: ${{ secrets.DEV_ROLE }}                 # REQUIRED
+          role-session-name: "${{ github.run_id }}-${{ github.run_attempt }}"                      # RECOMMENDED
+          role-duration-seconds: ${{ secrets.DEV_ROLE_DURATION }} # 15 mins - this is the minimum allowable duration  # RECOMMENDED
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3.1.2
+        with:
+          terraform_version: 'latest'
+
+      - name: Initialize Terraform
+        run: terraform init
+
+      - name: Plan terraform Changes
+        env:
+          TF_VAR_aws_region: ${{ github.event.inputs.aws-region }}
+          TF_VAR_environment: ${{ github.event.inputs.environment }}
+          TF_VAR_project_name: ${{ github.event.inputs.project-name }}
+          TF_VAR_project_id: ${{ github.event.inputs.project-id }}
+        run: terraform plan
+
+      - name: Plan terraform Changes
+        env:
+          TF_VAR_aws_region: ${{ github.event.inputs.aws-region }}
+          TF_VAR_environment: ${{ github.event.inputs.environment }}
+          TF_VAR_project_name: ${{ github.event.inputs.project-name }}
+          TF_VAR_project_id: ${{ github.event.inputs.project-id }}
+        run: terraform apply -auto-approve
+
+  terraform-deploy-us-west-2:
+    if: ${{ needs.verify.outputs.checkov_vpc_status == 'success' && inputs.aws-region == 'us-west-2' }}
+    needs: verify
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: aws/tools/003-once-to-many-per-region/001-setup-vpc/us-west-2
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v5
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v5.0.0
+        with:
+          aws-region: ${{ secrets.DEV_AWS_REGION }}               # REQUIRED
+          role-to-assume: ${{ secrets.DEV_ROLE }}                 # REQUIRED
+          role-session-name: "${{ github.run_id }}-${{ github.run_attempt }}"                      # RECOMMENDED
+          role-duration-seconds: ${{ secrets.DEV_ROLE_DURATION }} # 15 mins - this is the minimum allowable duration  # RECOMMENDED
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v3.1.2
+        with:
+          terraform_version: 'latest'
+
+      - name: Initialize Terraform
+        run: terraform init
+
+      - name: Plan terraform Changes
+        env:
+          TF_VAR_aws_region: ${{ github.event.inputs.aws-region }}
+          TF_VAR_environment: ${{ github.event.inputs.environment }}
+          TF_VAR_project_name: ${{ github.event.inputs.project-name }}
+          TF_VAR_project_id: ${{ github.event.inputs.project-id }}
+        run: terraform plan
+
+      - name: Plan terraform Changes
+        env:
+          TF_VAR_aws_region: ${{ github.event.inputs.aws-region }}
+          TF_VAR_environment: ${{ github.event.inputs.environment }}
+          TF_VAR_project_name: ${{ github.event.inputs.project-name }}
+          TF_VAR_project_id: ${{ github.event.inputs.project-id }}
+        run: terraform apply -auto-approve
+
+
+# https://dev.to/terrateam/building-a-cicd-pipeline-for-terraform-with-github-actions-step-by-step-guide-3dlp
+# deals with how to save a plan and execute
+# https://medium.com/@kiran007anil/automating-terraform-deployments-with-github-actions-3a3d8f78b49d
